const dialog=document.querySelector('#dialog');
const title=document.querySelector('#dialog-title');
const body=document.querySelector('#dialog-body');
let trigger;
function openDialog(t,html){trigger=document.activeElement;title.textContent=t;body.innerHTML=html;dialog.showModal();}
document.querySelector('.dialog-close').onclick=()=>dialog.close();
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>trigger?.focus());
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x[0]===b.dataset.product);openDialog(p[1],`<p>${p[2]}</p><div class="pills" style="margin-top:20px">${p[3].map(x=>`<span>${x}</span>`).join('')}</div><p class="form-note">Полная страница продукта — следующий этап.</p><button class="btn" id="discuss">Обсудить задачу →</button>`);body.querySelector('#discuss').onclick=()=>{dialog.close();revealContact();document.querySelector('#message').value=`Интересует: ${p[1]}`;document.querySelector('#contact').scrollIntoView();document.querySelector('#message').focus({preventScroll:true});};});
document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>{openDialog(b.dataset.info,'<p></p>');body.querySelector('p').textContent=b.dataset.description||'Раздел подготовлен в структуре сайта. Его содержание добавим на следующем этапе.';});
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{const track=document.getElementById(b.dataset.track);track.scrollBy({left:Number(b.dataset.scroll)*(track.firstElementChild.getBoundingClientRect().width+20),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{openDialog('Найдите свой продукт','<label for="product-search">Что вам нужно?</label><div style="display:flex;gap:8px;margin-top:10px"><input id="product-search" placeholder="Например, сервер или почта"><button id="clear-search" aria-label="Очистить поиск" hidden>×</button></div><div class="search-results"></div>');const input=body.querySelector('input'),list=body.querySelector('.search-results'),clear=body.querySelector('#clear-search');function render(){clear.hidden=!input.value;const found=products.filter(p=>p.join(' ').toLowerCase().includes(input.value.trim().toLowerCase()));list.replaceChildren();if(!found.length){const p=document.createElement('p');p.textContent='Ничего не найдено. Попробуйте «хостинг», «VPS» или «почта».';list.append(p);}found.forEach(p=>{const b=document.createElement('button');b.textContent=p[1]+' →';b.onclick=()=>{dialog.close();document.getElementById(p[0]).scrollIntoView();document.querySelector(`[data-product="${p[0]}"]`).focus({preventScroll:true});};list.append(b);});}input.oninput=render;clear.onclick=()=>{input.value='';render();input.focus();};render();input.focus();});
function revealContact(){document.querySelector('#contact-extra').hidden=false;document.querySelector('#message').setAttribute('aria-expanded','true');document.querySelector('#contact-form button[type=submit]').innerHTML='Проверить заявку →';}
document.querySelector('#message').addEventListener('input',e=>{if(e.target.value.trim())revealContact();});
document.querySelector('#contact-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,status=form.querySelector('.form-status');if(document.querySelector('#contact-extra').hidden){revealContact();document.querySelector('#message').focus();return;}const fields=[form.elements.message,form.elements.name,form.elements.email];fields.forEach(f=>{f.removeAttribute('aria-invalid');f.setAttribute('aria-describedby','contact-status');});status.id='contact-status';const invalid=fields.find(f=>!f.value.trim()||(f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.value)));if(invalid){invalid.setAttribute('aria-invalid','true');status.textContent=invalid.type==='email'?'Укажите email в формате name@company.am.':'Заполните задачу и имя, чтобы проверить заявку.';invalid.focus();return;}status.textContent='Заявка заполнена. Это прототип: отправка не подключена, данные остались только на странице.';};
document.querySelector('[data-migrate]').onclick=()=>{openDialog('Что будем переносить?',`<p>Можно выбрать несколько услуг. Детали переноса согласуем с вами.</p><div class="choices">${['Сайт','VPS','Выделенный сервер','Почта','База данных','Другая инфраструктура'].map(t=>`<label><input type="checkbox" value="${t}">${t}</label>`).join('')}</div><p id="migration-status" role="status"></p><button class="btn" id="migration-next">Продолжить →</button>`);body.querySelector('#migration-next').onclick=()=>{const selected=[...body.querySelectorAll('input:checked')].map(i=>i.value);if(!selected.length){body.querySelector('#migration-status').textContent='Выберите хотя бы одну услугу.';return;}dialog.close();revealContact();const input=document.querySelector('#message');input.value='Перенос: '+selected.join(', ');document.querySelector('#contact').scrollIntoView();input.focus({preventScroll:true});};};
