const dialog=document.getElementById('dialog'),dialogTitle=document.getElementById('dialog-title'),dialogBody=document.getElementById('dialog-body');
let previousFocus,migrationSelection=[];
function openDialog(title,markup){previousFocus=document.activeElement;dialogTitle.textContent=title;dialogBody.innerHTML=markup;dialog.showModal();}
document.querySelector('.dialog-close').onclick=()=>dialog.close();
dialog.addEventListener('close',()=>previousFocus?.focus());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>{closeMenus();openDialog(b.dataset.info,'<p></p>');dialogBody.querySelector('p').textContent=b.dataset.description||'Содержание раздела будет добавлено на следующем этапе.';});
const menuButtons=[...document.querySelectorAll('[data-menu]')],header=document.querySelector('header');let leaveTimer;
function closeMenus(){document.querySelectorAll('.mega-panel').forEach(p=>p.hidden=true);menuButtons.forEach(b=>b.setAttribute('aria-expanded','false'));clearTimeout(leaveTimer);}
function openMenu(button){clearTimeout(leaveTimer);closeMenus();document.getElementById('menu-'+button.dataset.menu).hidden=false;button.setAttribute('aria-expanded','true');}
menuButtons.forEach(b=>{b.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&matchMedia('(min-width:761px)').matches)openMenu(b);});b.addEventListener('click',()=>b.getAttribute('aria-expanded')==='true'?closeMenus():openMenu(b));b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();openMenu(b);document.querySelector('#menu-'+b.dataset.menu+' a').focus();}});});
header.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')leaveTimer=setTimeout(closeMenus,180);});header.addEventListener('pointerenter',()=>clearTimeout(leaveTimer));
header.addEventListener('focusout',()=>setTimeout(()=>{if(!header.contains(document.activeElement))closeMenus();},0));
document.querySelectorAll('[data-close-menu]').forEach(b=>b.onclick=()=>{const active=menuButtons.find(b=>b.getAttribute('aria-expanded')==='true');closeMenus();active?.focus();});
document.addEventListener('click',e=>{if(!header.contains(e.target))closeMenus();});
const burger=document.querySelector('.utility-burger'),utility=document.querySelector('#utility-menu');
function closeUtility(){utility.classList.remove('open');burger.setAttribute('aria-expanded','false');}
burger.onclick=()=>{const open=burger.getAttribute('aria-expanded')!=='true';burger.setAttribute('aria-expanded',String(open));utility.classList.toggle('open',open);};
document.addEventListener('click',e=>{if(!e.target.closest('.topbar'))closeUtility();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const active=menuButtons.find(b=>b.getAttribute('aria-expanded')==='true');closeMenus();if(active)active.focus();if(burger.getAttribute('aria-expanded')==='true'){closeUtility();burger.focus();}}});
document.querySelectorAll('.mega-panel a,.utility-links a').forEach(a=>a.addEventListener('click',()=>{closeMenus();closeUtility();}));
const main=document.querySelector('main'),route=document.querySelector('#route-view');
function showRoute(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch{hash='';}const parts=hash.split('/');const isRoute=['product','service','info'].includes(parts[0]);main.hidden=isRoute;route.hidden=!isRoute;closeMenus();if(!isRoute){document.title='Entra — Облачные сервисы и инфраструктура';return;}
let title,description,pills=[];
if(parts[0]==='product'){const p=products.find(p=>p[0]===parts[1]);if(p){title=p[1];description=p[2];pills=p[3];}}
if(parts[0]==='service'){const s=services[Number(parts[1])];if(s){title=s[0];description=s[1];pills=s[2];}}
if(parts[0]==='info'){title=parts.slice(1).join('/');description='Содержание этого раздела подготовим на следующем этапе.';}
const content=route.querySelector('.route-content');content.replaceChildren();const eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent='ENTRA / ПРОДУКТЫ И УСЛУГИ';const h=document.createElement('h1');h.textContent=title||'Страница не найдена';const p=document.createElement('p');p.textContent=description||'Вернитесь в каталог и выберите продукт.';const tagBlock=document.createElement('div');tagBlock.className='pills';pills.forEach(t=>{const span=document.createElement('span');span.textContent=t;tagBlock.append(span);});const a=document.createElement('a');a.className='btn';a.href='#contact';a.textContent='Обсудить задачу →';a.onclick=()=>{const radio=[...document.querySelectorAll('[name=service]')].find(x=>x.value===title);if(radio)radio.checked=true;};const note=document.createElement('p');note.className='route-note';note.textContent='Краткая страница продукта. Подробные условия и тарифы добавим на следующем этапе.';content.append(eyebrow,h,p,tagBlock,a,note);document.title=(title||'Страница не найдена')+' — Entra';scrollTo(0,0);route.focus({preventScroll:true});}
window.addEventListener('hashchange',showRoute);showRoute();
document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{closeMenus();openDialog('Найдите свой продукт','<label for="product-search">Что вам нужно?</label><div style="display:flex;gap:8px;margin-top:10px"><input id="product-search" placeholder="Например, сервер или почта"><button id="clear-search" aria-label="Очистить поиск" hidden>×</button></div><div class="search-results"></div>');const input=dialogBody.querySelector('input'),list=dialogBody.querySelector('.search-results'),clear=dialogBody.querySelector('#clear-search');function render(){clear.hidden=!input.value;const found=products.filter(p=>p.join(' ').toLowerCase().includes(input.value.trim().toLowerCase()));list.replaceChildren();if(!found.length){const p=document.createElement('p');p.textContent='Ничего не найдено. Попробуйте «хостинг», «VPS» или «почта».';list.append(p);}found.forEach(p=>{const a=document.createElement('a');a.className='search-result-link';a.style.cssText='display:block;padding:12px 0;border-bottom:1px solid #eee';a.textContent=p[1]+' →';a.href='#product/'+p[0];a.onclick=()=>dialog.close();list.append(a);});}input.oninput=render;clear.onclick=()=>{input.value='';render();input.focus();};render();input.focus();});
const contact=document.querySelector('#contact-form'),phone=document.querySelector('#phone'),extra=document.querySelector('#contact-extra'),status=document.querySelector('#contact-status');
const validPhone=()=>/^\+?[\d\s().-]+$/.test(phone.value.trim())&&phone.value.replace(/\D/g,'').length>=7&&phone.value.replace(/\D/g,'').length<=15;
function revealContact(){extra.hidden=false;phone.setAttribute('aria-expanded','true');contact.querySelector('[type=submit]').textContent='Свяжитесь со мной →';}
phone.addEventListener('input',()=>{phone.removeAttribute('aria-invalid');status.textContent='';if(validPhone())revealContact();});
contact.onsubmit=e=>{e.preventDefault();if(!validPhone()){phone.setAttribute('aria-invalid','true');status.textContent='Укажите номер телефона: от 7 до 15 цифр, можно с кодом страны.';phone.focus();return;}if(extra.hidden){revealContact();return;}if(!contact.querySelector('[name=service]:checked')){status.textContent='Выберите интересующую услугу.';contact.querySelector('[name=service]').focus();return;}status.textContent='Данные заполнены. Это демонстрационная форма: отправка пока не подключена.';};
document.querySelector('.domain-search').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector('input'),status=e.currentTarget.querySelector('.domain-status'),value=input.value.trim();if(!value||!value.includes('.')||/[\s/<>]/.test(value)){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby','domain-status');status.id='domain-status';status.textContent='Введите домен, например mycompany.am.';input.focus();return;}input.removeAttribute('aria-invalid');status.textContent='Проверка доступности домена будет подключена к регистратору. Результат пока не запрашивался.';};
document.querySelector('[data-migrate]').onclick=()=>{openDialog('Что будем переносить?',`<p>Можно выбрать несколько услуг.</p><div class="choices">${['Сайт','VPS','Выделенный сервер','Почта','База данных','Другая инфраструктура'].map(t=>`<label><input type="checkbox" value="${t}">${t}</label>`).join('')}</div><p id="migration-status" role="status"></p><button class="btn" id="migration-next">Продолжить →</button>`);dialogBody.querySelector('#migration-next').onclick=()=>{const selected=[...dialogBody.querySelectorAll('input:checked')].map(i=>i.value);if(!selected.length){dialogBody.querySelector('#migration-status').textContent='Выберите хотя бы одну услугу.';return;}migrationSelection=selected;dialog.close();const radio=[...contact.querySelectorAll('[name=service]')].find(r=>r.value==='Перенос проекта');radio.checked=true;const summary=document.querySelector('#migration-summary');summary.textContent='Переносим: '+selected.join(', ');summary.hidden=false;location.hash='contact';phone.focus({preventScroll:true});document.querySelector('#contact').scrollIntoView();};};
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
const counters=[...document.querySelectorAll('.stats strong')];const originalCounts=counters.map(el=>({el,text:el.textContent,value:Number(el.textContent.replace(/\D/g,'')),plus:el.textContent.includes('+')}));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;observer.unobserve(entry.target);const item=originalCounts.find(c=>c.el===entry.target);if(reduceMotion.matches)return;const start=performance.now();function tick(now){const p=Math.min((now-start)/1100,1);item.el.textContent=Math.round(item.value*(1-Math.pow(1-p,3))).toLocaleString('ru-RU')+(item.plus?'+':'');if(p<1)requestAnimationFrame(tick);else item.el.textContent=item.text;}requestAnimationFrame(tick);});},{threshold:.4});counters.forEach(c=>observer.observe(c));}
document.querySelectorAll('.metal-card').forEach(card=>card.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||reduceMotion.matches)return;const r=card.getBoundingClientRect();card.style.setProperty('--mx',((e.clientX-r.left)/r.width*100)+'%');card.style.setProperty('--my',((e.clientY-r.top)/r.height*100)+'%');}));
